import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
          <li>Past Bookings</li>
        </nav>
      <main className={styles.main}>
        <h3> Search for rinks</h3>
        <form>
          <input
          type="text"

          ></input>
          <input type="date"></input>
          <button
          type="submit">Search</button>
        </form>
        

      <h1>Search for free ice bookings below!</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          
        </a>
      </footer>
    </div>
  )
}
